### ISSUE TITLE
安卓 sendAuthRequest拿不到回调信息

### ISSUE THREAD

**Issue by aijason** [shm-open/react-native-wechat#113]
Please read and follow the issue templates:

1. Bug Report or Documentation Issue or Questions and Help?

2. Which `react-native-wechat` version are you using?

3. What platform does your issue occur on? (Android/iOS/Both)

4. Please provide a clear and concise description of what the bug is as precisely as possible，you can: 

  1) post a screenshot to explain in which case you get the issue?  
  2) related `logs`？  
  3) show us the code you are using?
  4) others.

### Your Environment

| software         | version
| ---------------- | -------
| react-native-wechat |  ^ version
| react-native     | ^ version
| node             | ^ version
| npm or yarn      | ^ version

**Comment by LittleXianyu** [comment]
可以提供一些调用的代码信息么？sendAuthRequest自测可获取回调信息且在线上稳定运行。

**Comment by aijason** [comment]
已经解决了 创建文件夹的路径名称跟包名不一致导致的。
